using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using HotelManagementSystem.Contracts;
using HotelManagementSystem.Domain;
using HotelManagementSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace HotelManagementSystem.Application;
public class DomainException(string message) : Exception(message);
public sealed record CancellationResult(decimal Fee, bool EmailSent);
public interface IEmailSender { Task SendAsync(string recipient,string subject,string body); }
public class AuthService(HmsDbContext db, IConfiguration config, IEmailSender email)
{
 public async Task<object> RegisterGuest(GuestRegisterRequest r) { if(r.Password.Length<8||!r.Password.Any(char.IsUpper)||!r.Password.Any(c=>!char.IsLetterOrDigit(c)))throw new DomainException("Password must have at least 8 characters, one uppercase letter, and one symbol (for example ! or @)."); if(await db.Users.AnyAsync(x=>x.Email==r.Email)||await db.Guests.AnyAsync(x=>x.PersonalNumber==r.PersonalNumber||x.PhoneNumber==r.PhoneNumber)) throw new DomainException("Email, personal number, or phone number is already registered."); var g=new Guest { FirstName=r.FirstName,LastName=r.LastName,PersonalNumber=r.PersonalNumber,PhoneNumber=r.PhoneNumber}; db.Guests.Add(g); await db.SaveChangesAsync(); var u=new AppUser { Email=r.Email,PasswordHash=BCrypt.Net.BCrypt.HashPassword(r.Password),Role="Guest",GuestId=g.Id};db.Users.Add(u);await db.SaveChangesAsync();await SendCode(u,"EmailVerification","Confirm your email address");return new { message="A verification code was sent to your email address."}; }
 public async Task<object> ConfirmEmail(EmailCodeRequest r) { var u=await db.Users.SingleOrDefaultAsync(x=>x.Email==r.Email)??throw new DomainException("Invalid verification code.");await ConsumeCode(u,r.Code,"EmailVerification");u.EmailConfirmed=true;await db.SaveChangesAsync();return new {message="Email verified. You can now log in."}; }
 public async Task<object> ResendEmailConfirmation(string emailAddress) { var u=await db.Users.SingleOrDefaultAsync(x=>x.Email==emailAddress)??throw new DomainException("No account exists for this email address.");if(u.EmailConfirmed)throw new DomainException("This email address is already confirmed. Please log in.");await SendCode(u,"EmailVerification","Confirm your email address");return new {message="A new verification code was sent to your email address."}; }
 public async Task<object> ForgotPassword(string emailAddress){var u=await db.Users.SingleOrDefaultAsync(x=>x.Email==emailAddress);if(u is null)return new{message="If an account exists for that email, a new temporary password was sent."};var temporary=CreateTemporaryPassword();await email.SendAsync(u.Email,"Your new Vacay password",$"You asked to reset your Vacay password.\n\nYour new temporary password is: {temporary}\n\nUse it to log in, then keep it private. If you did not request this, contact Vacay support.");u.PasswordHash=BCrypt.Net.BCrypt.HashPassword(temporary);u.EmailConfirmed=true;await db.SaveChangesAsync();return new{message="A new temporary password was sent to your email. You can log in immediately."};}
 public async Task<object> ChangePassword(int userId,ChangePasswordRequest r){var u=await db.Users.FindAsync(userId)??throw new DomainException("Account not found.");if(!BCrypt.Net.BCrypt.Verify(r.CurrentPassword,u.PasswordHash))throw new DomainException("Your current password is incorrect.");if(r.NewPassword.Length<8||!r.NewPassword.Any(char.IsUpper)||!r.NewPassword.Any(c=>!char.IsLetterOrDigit(c)))throw new DomainException("New password must have at least 8 characters, one uppercase letter, and one symbol.");u.PasswordHash=BCrypt.Net.BCrypt.HashPassword(r.NewPassword);await db.SaveChangesAsync();return new{message="Password changed successfully. Use your new password next time you log in."};}
 public async Task<object> Login(LoginRequest r) { var u=await db.Users.SingleOrDefaultAsync(x=>x.Email==r.Email) ?? throw new DomainException("Invalid email or password."); if(!BCrypt.Net.BCrypt.Verify(r.Password,u.PasswordHash)) throw new DomainException("Invalid email or password.");if(!u.EmailConfirmed)throw new DomainException("Confirm your email before logging in.");return new {token=CreateToken(u),role=u.Role}; }
 public async Task<object> ConfirmLogin(EmailCodeRequest r) {var u=await db.Users.SingleOrDefaultAsync(x=>x.Email==r.Email)??throw new DomainException("Invalid login code.");await ConsumeCode(u,r.Code,"Login");return new {token=CreateToken(u),role=u.Role};}
 async Task SendCode(AppUser u,string purpose,string subject){var old=await db.EmailCodes.Where(x=>x.UserId==u.Id&&x.Purpose==purpose&&!x.Used).ToListAsync();foreach(var c in old)c.Used=true;var code=RandomNumberGenerator.GetInt32(100000,1000000).ToString();db.EmailCodes.Add(new EmailCode{UserId=u.Id,Purpose=purpose,CodeHash=Hash(code),ExpiresAtUtc=DateTime.UtcNow.AddMinutes(10)});await db.SaveChangesAsync();await email.SendAsync(u.Email,subject,$"Your Vacay verification code is {code}. It expires in 10 minutes.");}
 async Task ConsumeCode(AppUser u,string code,string purpose){var item=await db.EmailCodes.OrderByDescending(x=>x.Id).FirstOrDefaultAsync(x=>x.UserId==u.Id&&x.Purpose==purpose&&!x.Used&&x.ExpiresAtUtc>DateTime.UtcNow&&x.CodeHash==Hash(code))??throw new DomainException("The code is invalid or expired.");item.Used=true;await db.SaveChangesAsync();}
 static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)));
 static string CreateTemporaryPassword(){const string letters="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";const string symbols="!@#$%";return "V"+string.Concat(Enumerable.Range(0,7).Select(_=>letters[RandomNumberGenerator.GetInt32(letters.Length)]))+symbols[RandomNumberGenerator.GetInt32(symbols.Length)];}
 public string CreateToken(AppUser u) { var key=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(config["Jwt:Key"]!)); var claims=new List<Claim>{new(ClaimTypes.NameIdentifier,u.Id.ToString()),new(ClaimTypes.Email,u.Email),new(ClaimTypes.Role,u.Role)}; if(u.GuestId.HasValue) claims.Add(new("guestId",u.GuestId.Value.ToString())); if(u.ManagerId.HasValue) claims.Add(new("managerId",u.ManagerId.Value.ToString())); return new JwtSecurityTokenHandler().WriteToken(new JwtSecurityToken(issuer:config["Jwt:Issuer"],audience:config["Jwt:Audience"],claims:claims,expires:DateTime.UtcNow.AddYears(1),signingCredentials:new SigningCredentials(key,SecurityAlgorithms.HmacSha256))); }
}
public class ReservationService(HmsDbContext db,IEmailSender email)
{
 public async Task<Reservation> Create(int guestId, ReservationRequest r) { ValidateDates(r.CheckInDate,r.CheckOutDate); if(r.RoomIds.Count==0||r.RoomIds.Count!=r.RoomIds.Distinct().Count()) throw new DomainException("Select one or more distinct rooms."); var rooms=await db.Rooms.Where(x=>r.RoomIds.Contains(x.Id)).Include(x=>x.Hotel).ToListAsync(); if(rooms.Count!=r.RoomIds.Count) throw new DomainException("One or more rooms do not exist."); if(await IsUnavailable(r.RoomIds,r.CheckInDate,r.CheckOutDate)) throw new DomainException("One or more rooms are unavailable for these dates."); var res=new Reservation{GuestId=guestId,CheckInDate=r.CheckInDate,CheckOutDate=r.CheckOutDate}; res.ReservationRooms=rooms.Select(x=>new ReservationRoom{RoomId=x.Id}).ToList(); db.Reservations.Add(res); await db.SaveChangesAsync();var user=await db.Users.SingleAsync(x=>x.GuestId==guestId);var first=rooms[0];var nights=r.CheckOutDate.DayNumber-r.CheckInDate.DayNumber;var host=new[]{"Nino","Giorgi","Ana","Luka"}[first.HotelId%4];await email.SendAsync(user.Email,"Vacay reservation confirmed",$"Your Vacay reservation is confirmed!\n\nProperty: {first.Hotel.Name}\nLocation: {first.Hotel.City}, Georgia\nRoom: {first.Name}\nCheck-in: {r.CheckInDate:dd MMM yyyy}\nCheck-out: {r.CheckOutDate:dd MMM yyyy}\nNights: {nights}\nYour host: {host}\nPayment: Pay at the property\n\nWe cannot wait to welcome you to Georgia."); return res; }
 public async Task UpdateDates(Reservation r, ReservationDatesRequest d) { ValidateDates(d.CheckInDate,d.CheckOutDate); var ids=await db.ReservationRooms.Where(x=>x.ReservationId==r.Id).Select(x=>x.RoomId).ToListAsync(); if(await IsUnavailable(ids,d.CheckInDate,d.CheckOutDate,r.Id)) throw new DomainException("The new dates overlap another reservation."); r.CheckInDate=d.CheckInDate;r.CheckOutDate=d.CheckOutDate;await db.SaveChangesAsync(); }
 public async Task<CancellationResult> Cancel(Reservation reservation){var room=await db.ReservationRooms.Where(x=>x.ReservationId==reservation.Id).Select(x=>new{x.Room,x.Room.Hotel}).FirstAsync();var nights=reservation.CheckOutDate.DayNumber-reservation.CheckInDate.DayNumber;var fee=Math.Round(room.Room.Price*nights*.10m,2);var emailSent=false;try{var user=await db.Users.SingleAsync(x=>x.GuestId==reservation.GuestId);await email.SendAsync(user.Email,"Vacay reservation cancelled",$"Your reservation has been cancelled.\n\nProperty: {room.Hotel.Name}\nLocation: {room.Hotel.City}, Georgia\nDates: {reservation.CheckInDate:dd MMM yyyy} - {reservation.CheckOutDate:dd MMM yyyy}\nCancellation fee: ${fee:0.00}\n\nWe hope to welcome you on another Vacay trip.");emailSent=true;}catch(Exception){/* Cancellation must complete even when the email provider is unavailable. */}db.Reservations.Remove(reservation);await db.SaveChangesAsync();return new CancellationResult(fee,emailSent);}
 public Task<bool> IsUnavailable(IEnumerable<int> ids,DateOnly start,DateOnly end,int? except=null)=>db.ReservationRooms.Where(x=>ids.Contains(x.RoomId)&&(!except.HasValue||x.ReservationId!=except)).AnyAsync(x=>x.Reservation.CheckInDate<end&&x.Reservation.CheckOutDate>start);
 static void ValidateDates(DateOnly a,DateOnly b) { if(a<DateOnly.FromDateTime(DateTime.UtcNow.Date)) throw new DomainException("Check-in must be today or later."); if(b<=a) throw new DomainException("Check-out must be after check-in."); }
}
public class CarRentalService(HmsDbContext db,IEmailSender email)
{
 public async Task<CarRental> Create(int guestId,CarRentalRequest r)
 {
  if(string.IsNullOrWhiteSpace(r.DrivingLicenseId))throw new DomainException("A driving licence ID is required.");
  if(r.PickupDate<DateOnly.FromDateTime(DateTime.UtcNow)||r.DropoffDate<=r.PickupDate)throw new DomainException("Choose valid future pickup and drop-off dates.");
  var car=await db.Cars.FindAsync(r.CarId)??throw new DomainException("Car not found.");
  var unavailable=await db.CarRentals.AnyAsync(x=>x.CarId==r.CarId&&x.PickupDate<r.DropoffDate&&x.DropoffDate>r.PickupDate);
  if(unavailable)throw new DomainException("This car is unavailable for these dates.");
  var rental=new CarRental{CarId=car.Id,GuestId=guestId,PickupDate=r.PickupDate,DropoffDate=r.DropoffDate,DrivingLicenseId=r.DrivingLicenseId.Trim(),PickupLocation=string.IsNullOrWhiteSpace(r.PickupLocation)?$"{car.City} city centre":r.PickupLocation.Trim()};
  db.CarRentals.Add(rental);
  await db.SaveChangesAsync();
  var user=await db.Users.SingleAsync(x=>x.GuestId==guestId);
  var days=r.DropoffDate.DayNumber-r.PickupDate.DayNumber;
  var total=car.DailyPrice*days*1.18m;
  try
  {
   await email.SendAsync(user.Email,"Vacay car rental confirmed",$"Your Vacay car rental is confirmed!\n\nCar: {car.Brand} {car.Model} ({car.Year})\nCity: {car.City}, Georgia\nPick-up: {r.PickupDate:dd MMM yyyy}, {rental.PickupLocation}\nDrop-off: {r.DropoffDate:dd MMM yyyy}\nRental days: {days}\nTotal including taxes: ${total:0.00}\nPayment: Pay at pick-up\n\nPlease bring your driving licence and booking confirmation.");
  }
  catch(Exception) { /* The booking is already saved; an unavailable email service must not turn it into a failed rental. */ }
  return rental;
 }
 public async Task<CancellationResult> Cancel(CarRental rental)
 {
  var car=await db.Cars.FindAsync(rental.CarId)??throw new DomainException("Car not found.");
  var days=rental.DropoffDate.DayNumber-rental.PickupDate.DayNumber;
  var fee=Math.Round(car.DailyPrice*days*.10m,2);
  var user=await db.Users.SingleAsync(x=>x.GuestId==rental.GuestId);
  var emailSent=false;
  try
  {
   await email.SendAsync(user.Email,"Vacay car rental cancelled",$"Your Vacay car rental has been cancelled.\n\nCar: {car.Brand} {car.Model} ({car.Year})\nCity: {car.City}, Georgia\nPick-up: {rental.PickupDate:dd MMM yyyy}, {rental.PickupLocation}\nDrop-off: {rental.DropoffDate:dd MMM yyyy}\nCancellation fee: ${fee:0.00}\n\nWe hope to see you on another Vacay trip.");
   emailSent=true;
   }
  catch(Exception) { /* Cancellation must complete even when the email provider is temporarily unavailable. */ }
  db.CarRentals.Remove(rental);
  await db.SaveChangesAsync();
  return new CancellationResult(fee,emailSent);
 }
}
public class HostChatService(HmsDbContext db)
{
 public async Task<List<HostMessage>> Send(int reservationId,int guestId,string body){if(string.IsNullOrWhiteSpace(body))throw new DomainException("Write a message before sending.");var reservation=await db.Reservations.Include(x=>x.ReservationRooms).ThenInclude(x=>x.Room).ThenInclude(x=>x.Hotel).SingleOrDefaultAsync(x=>x.Id==reservationId&&x.GuestId==guestId)??throw new DomainException("Reservation not found.");db.HostMessages.Add(new HostMessage{ReservationId=reservationId,GuestId=guestId,Sender="Guest",Body=body.Trim(),SentAtUtc=DateTime.UtcNow});var room=reservation.ReservationRooms.FirstOrDefault()?.Room;var reply=Reply(body,room?.Hotel.City??"Georgia",room?.Hotel.Address??"the property",room?.Name??"your room");db.HostMessages.Add(new HostMessage{ReservationId=reservationId,GuestId=guestId,Sender="Host Nino",Body=reply,SentAtUtc=DateTime.UtcNow.AddSeconds(1)});await db.SaveChangesAsync();return await Messages(reservationId,guestId);}
 public Task<List<HostMessage>> Messages(int reservationId,int guestId)=>db.HostMessages.Where(x=>x.ReservationId==reservationId&&x.GuestId==guestId).OrderBy(x=>x.SentAtUtc).ToListAsync();
 static string Reply(string message,string city,string address,string room){var q=message.ToLowerInvariant();var local=city switch{"Tbilisi"=>"the Old Town, Narikala Fortress, Abanotubani sulfur baths, and Fabrika", "Batumi"=>"Batumi Boulevard, the Ali and Nino statue, Europe Square, and the Botanical Garden", "Kutaisi"=>"Bagrati Cathedral, the central market, Gelati Monastery, and Prometheus Cave", "Kazbegi"=>"Gergeti Trinity Church, Dariali Gorge, and the mountain viewpoints", "Telavi"=>"Batonistsikhe Fortress, Tsinandali Estate, and Kakheti family wine cellars", "Mestia"=>"the Svaneti Museum, historic towers, Hatsvali, and the road to Ushguli", "Kobuleti"=>"Kobuleti Beach, Petra Fortress, and Mtirala National Park", _=>"the main sights and local cafés"};if(q.Contains("check-in")||q.Contains("check in")||q.Contains("instruction")||q.Contains("arrival")||q.Contains("arrive")||q.Contains("key")||q.Contains("door")||q.Contains("access"))return $"Check-in for {room} is from 15:00 and check-out is by 11:00. The property is at {address}. On arrival, message me and I will send the entrance and key instructions. Please bring the ID used for the reservation.";if(q.Contains("address")||q.Contains("adress")||q.Contains("location")||q.Contains("where are you"))return $"The property address is {address}. It is in {city}, Georgia. I will send the entrance details before your arrival.";if(q.Contains("local")||q.Contains("place")||q.Contains("visit")||q.Contains("sight")||q.Contains("restaurant")||q.Contains("café")||q.Contains("cafe")||q.Contains("eat")||q.Contains("thing to do"))return $"For local places in {city}, I recommend {local}. Tell me what you enjoy and I can suggest a route and nearby food options.";if(q.Contains("breakfast"))return "Breakfast is served from 08:00 to 11:00. I can confirm the included option for your room and recommend nearby cafés if you prefer to eat out.";if(q.Contains("airport")||q.Contains("transfer"))return $"I can help arrange a transfer to {city}. Please send your flight arrival time, terminal, and number of guests.";if(q.Contains("parking"))return "Nearby parking is available. Message me with your arrival time and I will send the closest entrance and parking instructions.";if(q.Contains("cancel"))return "You can cancel from My stays while signed in. The fee is shown before confirmation, and the reservation is removed immediately after you accept.";if(q.Contains("hello")||q.Contains("hi"))return $"Hello! I am Host Nino for your stay in {city}. I can help with check-in, breakfast, transport, parking, or local places.";return "I can help with a specific question about check-in, the address, breakfast, parking, transfers, or local places. Please tell me what you need.";}
}
