using System.Security.Claims;
using HotelManagementSystem.Application;
using HotelManagementSystem.Contracts;
using HotelManagementSystem.Domain;
using HotelManagementSystem.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace HotelManagementSystem.Controllers;
[ApiController, Route("api/hotels/{hotelId:int}")]
public class HotelResourcesController(HmsDbContext db, ReservationService reservations) : ControllerBase
{
 [ResponseCache(NoStore=true,Location=ResponseCacheLocation.None)]
 [HttpGet("rooms")] public async Task<ActionResult<ApiResponse<object>>> Rooms(int hotelId,decimal? minPrice,decimal? maxPrice,DateOnly? checkIn,DateOnly? checkOut) {var q=db.Rooms.AsNoTracking().Where(x=>x.HotelId==hotelId);if(minPrice.HasValue)q=q.Where(x=>x.Price>=minPrice);if(maxPrice.HasValue)q=q.Where(x=>x.Price<=maxPrice);if(checkIn.HasValue&&checkOut.HasValue){var unavailable=db.ReservationRooms.Where(x=>x.Reservation.CheckInDate<checkOut&&x.Reservation.CheckOutDate>checkIn).Select(x=>x.RoomId);q=q.Where(x=>!unavailable.Contains(x.Id));}return Ok(new ApiResponse<object>(true,await q.ToListAsync()));}
 [HttpGet("rooms/{roomId:int}")] public async Task<ActionResult<ApiResponse<Room>>> Room(int hotelId,int roomId){var r=await db.Rooms.SingleOrDefaultAsync(x=>x.Id==roomId&&x.HotelId==hotelId);return r is null?NotFound(new ApiResponse<Room>(false,null,"Room not found.")):Ok(new ApiResponse<Room>(true,r));}
 [Authorize(Roles="Admin,Manager"),HttpPost("rooms")] public async Task<ActionResult<ApiResponse<object>>> AddRoom(int hotelId,[FromBody] RoomRequest? r){if(r is null)throw new DomainException("Room details are required.");if(r.Price<=0||r.Capacity<1||r.SizeSquareMeters<1||string.IsNullOrWhiteSpace(r.Name))throw new DomainException("Room name, positive price, capacity, and size are required.");if(!await db.Hotels.AnyAsync(x=>x.Id==hotelId))throw new DomainException("Hotel not found.");var room=new Room{Name=r.Name.Trim(),Price=r.Price,Capacity=r.Capacity,SizeSquareMeters=r.SizeSquareMeters,BreakfastIncluded=r.BreakfastIncluded,HotelId=hotelId};db.Rooms.Add(room);await db.SaveChangesAsync();return CreatedAtAction(nameof(Room),new{hotelId,roomId=room.Id},new ApiResponse<object>(true,new {room.Id,room.Name,room.Price,room.Capacity,room.SizeSquareMeters,room.BreakfastIncluded,room.HotelId},"Room created and is now live."));}
 [Authorize(Roles="Admin,Manager"),HttpPut("rooms/{roomId:int}")] public async Task<ActionResult<ApiResponse<Room>>> UpdateRoom(int hotelId,int roomId,RoomRequest r){if(r.Price<=0)throw new DomainException("Price must be greater than zero.");var room=await db.Rooms.SingleOrDefaultAsync(x=>x.Id==roomId&&x.HotelId==hotelId)??throw new DomainException("Room not found.");room.Name=r.Name;room.Price=r.Price;await db.SaveChangesAsync();return Ok(new ApiResponse<Room>(true,room));}
 [Authorize(Roles="Admin,Manager"),HttpDelete("rooms/{roomId:int}")] public async Task<IActionResult> DeleteRoom(int hotelId,int roomId){var room=await db.Rooms.SingleOrDefaultAsync(x=>x.Id==roomId&&x.HotelId==hotelId)??throw new DomainException("Room not found.");if(await db.ReservationRooms.AnyAsync(x=>x.RoomId==roomId&&x.Reservation.CheckOutDate>=DateOnly.FromDateTime(DateTime.UtcNow)))throw new DomainException("Room has an active or future reservation.");db.Rooms.Remove(room);await db.SaveChangesAsync();return NoContent();}
 [Authorize(Roles="Admin"),HttpPost("managers")] public async Task<ActionResult<ApiResponse<Manager>>> AddManager(int hotelId,ManagerRequest r){if(!await db.Hotels.AnyAsync(x=>x.Id==hotelId))throw new DomainException("Hotel not found.");if(await db.Managers.AnyAsync(x=>x.Email==r.Email||x.PersonalNumber==r.PersonalNumber)||await db.Users.AnyAsync(x=>x.Email==r.Email))throw new DomainException("Email or personal number is already registered.");var m=new Manager{FirstName=r.FirstName,LastName=r.LastName,PersonalNumber=r.PersonalNumber,Email=r.Email,PhoneNumber=r.PhoneNumber,HotelId=hotelId};db.Managers.Add(m);await db.SaveChangesAsync();db.Users.Add(new AppUser{Email=r.Email,PasswordHash=BCrypt.Net.BCrypt.HashPassword(r.Password),Role="Manager",ManagerId=m.Id});await db.SaveChangesAsync();return Ok(new ApiResponse<Manager>(true,m));}
 [Authorize(Roles="Guest"),HttpPost("reservations")] public async Task<ActionResult<ApiResponse<object>>> CreateReservation(int hotelId,ReservationRequest r){var rooms=await db.Rooms.Where(x=>x.HotelId==hotelId&&r.RoomIds.Contains(x.Id)).CountAsync();if(rooms!=r.RoomIds.Count)throw new DomainException("All reserved rooms must belong to this hotel.");var guestId=int.Parse(User.FindFirstValue("guestId")!);var res=await reservations.Create(guestId,r);return Ok(new ApiResponse<object>(true,new{res.Id,res.CheckInDate,res.CheckOutDate}));}
}
