using System.Security.Claims;
using HotelManagementSystem.Application;
using HotelManagementSystem.Contracts;
using HotelManagementSystem.Domain;
using HotelManagementSystem.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace HotelManagementSystem.Controllers;
[ApiController]
public class PeopleController(HmsDbContext db):ControllerBase
{
 [Authorize(Roles="Admin,Manager"),HttpPut("api/managers/{id:int}")] public async Task<ActionResult<ApiResponse<Manager>>> UpdateManager(int id,ManagerRequest r){var m=await db.Managers.FindAsync(id)??throw new DomainException("Manager not found.");if(await db.Managers.AnyAsync(x=>x.Id!=id&&(x.Email==r.Email||x.PersonalNumber==r.PersonalNumber)))throw new DomainException("Email or personal number is already registered.");m.FirstName=r.FirstName;m.LastName=r.LastName;m.PersonalNumber=r.PersonalNumber;m.Email=r.Email;m.PhoneNumber=r.PhoneNumber;await db.SaveChangesAsync();return Ok(new ApiResponse<Manager>(true,m));}
 [Authorize(Roles="Admin"),HttpDelete("api/managers/{id:int}")] public async Task<IActionResult> DeleteManager(int id){var m=await db.Managers.FindAsync(id)??throw new DomainException("Manager not found.");if(await db.Managers.CountAsync(x=>x.HotelId==m.HotelId)<=1)throw new DomainException("A hotel must retain at least one manager.");var u=await db.Users.SingleOrDefaultAsync(x=>x.ManagerId==id);if(u is not null)db.Users.Remove(u);db.Managers.Remove(m);await db.SaveChangesAsync();return NoContent();}
 [Authorize(Roles="Guest"),HttpGet("api/guests/me")] public async Task<ActionResult<ApiResponse<Guest>>> Me(){var id=int.Parse(User.FindFirstValue("guestId")!);var g=await db.Guests.FindAsync(id)??throw new DomainException("Guest not found.");return Ok(new ApiResponse<Guest>(true,g));}
 [Authorize(Roles="Guest"),HttpPut("api/guests/me")] public async Task<ActionResult<ApiResponse<Guest>>> UpdateGuest(GuestUpdateRequest r){var id=int.Parse(User.FindFirstValue("guestId")!);var g=await db.Guests.FindAsync(id)??throw new DomainException("Guest not found.");if(await db.Guests.AnyAsync(x=>x.Id!=id&&(x.PersonalNumber==r.PersonalNumber||x.PhoneNumber==r.PhoneNumber)))throw new DomainException("Personal number or phone number is already registered.");g.FirstName=r.FirstName;g.LastName=r.LastName;g.PersonalNumber=r.PersonalNumber;g.PhoneNumber=r.PhoneNumber;await db.SaveChangesAsync();return Ok(new ApiResponse<Guest>(true,g));}
 [Authorize(Roles="Guest"),HttpGet("api/favorites")] public async Task<ActionResult<ApiResponse<object>>> Favorites(){var id=int.Parse(User.FindFirstValue("guestId")!);var items=await db.Favorites.Where(x=>x.GuestId==id).Include(x=>x.Hotel).Select(x=>x.Hotel).ToListAsync();return Ok(new ApiResponse<object>(true,items));}
 [Authorize(Roles="Guest"),HttpPost("api/favorites/{hotelId:int}")] public async Task<ActionResult<ApiResponse<object>>> AddFavorite(int hotelId){var guestId=int.Parse(User.FindFirstValue("guestId")!);if(!await db.Hotels.AnyAsync(x=>x.Id==hotelId))throw new DomainException("Hotel not found.");if(!await db.Favorites.AnyAsync(x=>x.GuestId==guestId&&x.HotelId==hotelId)){db.Favorites.Add(new Favorite{GuestId=guestId,HotelId=hotelId});await db.SaveChangesAsync();}return Ok(new ApiResponse<object>(true,new{message="Saved to favourites."}));}
 [Authorize(Roles="Guest"),HttpDelete("api/favorites/{hotelId:int}")] public async Task<IActionResult> RemoveFavorite(int hotelId){var guestId=int.Parse(User.FindFirstValue("guestId")!);var favorite=await db.Favorites.SingleOrDefaultAsync(x=>x.GuestId==guestId&&x.HotelId==hotelId)??throw new DomainException("Favourite not found.");db.Favorites.Remove(favorite);await db.SaveChangesAsync();return NoContent();}
 [Authorize(Roles="Guest"),HttpDelete("api/guests/me")] public async Task<IActionResult> DeleteGuest(){var id=int.Parse(User.FindFirstValue("guestId")!);if(await db.Reservations.AnyAsync(x=>x.GuestId==id&&x.CheckOutDate>=DateOnly.FromDateTime(DateTime.UtcNow)))throw new DomainException("A guest with active or future reservations cannot be deleted.");var g=await db.Guests.FindAsync(id)??throw new DomainException("Guest not found.");var u=await db.Users.SingleOrDefaultAsync(x=>x.GuestId==id);if(u is not null)db.Users.Remove(u);db.Guests.Remove(g);await db.SaveChangesAsync();return NoContent();}
}
