namespace HotelManagementSystem.Domain;

public class Hotel { public int Id { get; set; } public string Name { get; set; } = string.Empty; public int Rating { get; set; } public string Country { get; set; } = string.Empty; public string City { get; set; } = string.Empty; public string Address { get; set; } = string.Empty; public ICollection<Manager> Managers { get; set; } = new List<Manager>(); public ICollection<Room> Rooms { get; set; } = new List<Room>(); }
public class Manager { public int Id { get; set; } public string FirstName { get; set; } = string.Empty; public string LastName { get; set; } = string.Empty; public string PersonalNumber { get; set; } = string.Empty; public string Email { get; set; } = string.Empty; public string PhoneNumber { get; set; } = string.Empty; public int HotelId { get; set; } public Hotel Hotel { get; set; } = null!; }
public class Room { public int Id { get; set; } public string Name { get; set; } = string.Empty; public decimal Price { get; set; } public int Capacity { get; set; } public int SizeSquareMeters { get; set; } public bool BreakfastIncluded { get; set; } public int HotelId { get; set; } public Hotel Hotel { get; set; } = null!; public ICollection<ReservationRoom> ReservationRooms { get; set; } = new List<ReservationRoom>(); }
public class Guest { public int Id { get; set; } public string FirstName { get; set; } = string.Empty; public string LastName { get; set; } = string.Empty; public string PersonalNumber { get; set; } = string.Empty; public string PhoneNumber { get; set; } = string.Empty; public ICollection<Reservation> Reservations { get; set; } = new List<Reservation>(); }
public class Reservation { public int Id { get; set; } public DateOnly CheckInDate { get; set; } public DateOnly CheckOutDate { get; set; } public int GuestId { get; set; } public Guest Guest { get; set; } = null!; public ICollection<ReservationRoom> ReservationRooms { get; set; } = new List<ReservationRoom>(); }
public class ReservationRoom { public int ReservationId { get; set; } public Reservation Reservation { get; set; } = null!; public int RoomId { get; set; } public Room Room { get; set; } = null!; }
public class AppUser { public int Id { get; set; } public string Email { get; set; } = string.Empty; public string PasswordHash { get; set; } = string.Empty; public string Role { get; set; } = "Guest"; public bool EmailConfirmed { get; set; } public int? GuestId { get; set; } public int? ManagerId { get; set; } }
public class EmailCode { public int Id { get; set; } public int UserId { get; set; } public AppUser User { get; set; } = null!; public string CodeHash { get; set; } = string.Empty; public string Purpose { get; set; } = string.Empty; public DateTime ExpiresAtUtc { get; set; } public bool Used { get; set; } }
public class Favorite { public int Id { get; set; } public int GuestId { get; set; } public Guest Guest { get; set; } = null!; public int HotelId { get; set; } public Hotel Hotel { get; set; } = null!; }
public class Car { public int Id { get; set; } public string City { get; set; } = string.Empty; public string Brand { get; set; } = string.Empty; public string Model { get; set; } = string.Empty; public int Year { get; set; } public string Category { get; set; } = string.Empty; public decimal DailyPrice { get; set; } public int Seats { get; set; } public int Luggage { get; set; } public string Transmission { get; set; } = string.Empty; public string Fuel { get; set; } = string.Empty; public bool AirConditioning { get; set; } public bool UnlimitedKilometers { get; set; } public ICollection<CarRental> Rentals { get; set; } = new List<CarRental>(); }
public class CarRental { public int Id { get; set; } public int CarId { get; set; } public Car Car { get; set; } = null!; public int GuestId { get; set; } public Guest Guest { get; set; } = null!; public DateOnly PickupDate { get; set; } public DateOnly DropoffDate { get; set; } public string DrivingLicenseId { get; set; } = string.Empty; public string PickupLocation { get; set; } = string.Empty; }
public class ExperienceBooking { public int Id { get; set; } public int GuestId { get; set; } public Guest Guest { get; set; } = null!; public string City { get; set; } = string.Empty; public string Title { get; set; } = string.Empty; public string Category { get; set; } = string.Empty; public string Address { get; set; } = string.Empty; public DateOnly Date { get; set; } public TimeOnly ArrivalTime { get; set; } public decimal Price { get; set; } public int Participants { get; set; } }
public class HostMessage { public int Id { get; set; } public int ReservationId { get; set; } public Reservation Reservation { get; set; } = null!; public int GuestId { get; set; } public Guest Guest { get; set; } = null!; public string Sender { get; set; } = string.Empty; public string Body { get; set; } = string.Empty; public DateTime SentAtUtc { get; set; } }
