using HotelManagementSystem.Domain;
using Microsoft.EntityFrameworkCore;

namespace HotelManagementSystem.Infrastructure;
public class HmsDbContext(DbContextOptions<HmsDbContext> options) : DbContext(options)
{
 public DbSet<Hotel> Hotels => Set<Hotel>(); public DbSet<Manager> Managers => Set<Manager>(); public DbSet<Room> Rooms => Set<Room>(); public DbSet<Guest> Guests => Set<Guest>(); public DbSet<Reservation> Reservations => Set<Reservation>(); public DbSet<ReservationRoom> ReservationRooms => Set<ReservationRoom>(); public DbSet<AppUser> Users => Set<AppUser>(); public DbSet<EmailCode> EmailCodes => Set<EmailCode>(); public DbSet<Favorite> Favorites => Set<Favorite>(); public DbSet<Car> Cars => Set<Car>(); public DbSet<CarRental> CarRentals => Set<CarRental>(); public DbSet<ExperienceBooking> ExperienceBookings => Set<ExperienceBooking>(); public DbSet<HostMessage> HostMessages => Set<HostMessage>();
 protected override void OnModelCreating(ModelBuilder b) { base.OnModelCreating(b); b.Entity<Manager>().HasIndex(x=>x.Email).IsUnique(); b.Entity<Manager>().HasIndex(x=>x.PersonalNumber).IsUnique(); b.Entity<Guest>().HasIndex(x=>x.PersonalNumber).IsUnique(); b.Entity<Guest>().HasIndex(x=>x.PhoneNumber).IsUnique(); b.Entity<AppUser>().HasIndex(x=>x.Email).IsUnique(); b.Entity<Room>().Property(x=>x.Price).HasPrecision(18,2); b.Entity<Car>().Property(x=>x.DailyPrice).HasPrecision(18,2); b.Entity<ExperienceBooking>().Property(x=>x.Price).HasPrecision(18,2); b.Entity<ExperienceBooking>().HasOne(x=>x.Guest).WithMany().HasForeignKey(x=>x.GuestId).OnDelete(DeleteBehavior.Cascade); b.Entity<ReservationRoom>().HasKey(x=>new {x.ReservationId,x.RoomId}); b.Entity<Favorite>().HasIndex(x=>new{x.GuestId,x.HotelId}).IsUnique(); b.Entity<HostMessage>().HasOne(x=>x.Guest).WithMany().HasForeignKey(x=>x.GuestId).OnDelete(DeleteBehavior.NoAction); }
}
